/* eslint-disable sonarjs/no-duplicate-string */
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { Colors } from '../../../constants/colors';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const getStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background.primary,
      ...Platform.select({
        web: {
          paddingHorizontal: 0,
          marginHorizontal: 0,
        },
      }),
    },
    guestBanner: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingTop: 50,
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      borderBottomWidth: 1,
      borderBottomColor: Colors.border.light,
    },
    guestBannerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    guestBannerText: {
      fontSize: 14,
      fontWeight: '600',
      color: Colors.primary,
    },
    guestBannerCount: {
      fontSize: 12,
      color: Colors.text.secondary,
      marginLeft: 8,
    },
    guestSignUpButton: {
      backgroundColor: Colors.primary,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    guestSignUpButtonUrgent: {
      backgroundColor: Colors.accent.red,
      shadowColor: Colors.accent.red,
    },
    guestSignUpButtonText: {
      color: Colors.background.white,
      fontSize: 13,
      fontWeight: '700',
    },
    loginModalContainer: {
      flex: 1,
      backgroundColor: Colors.background.white,
    },
    loginModalHeader: {
      paddingTop: 50,
      paddingHorizontal: 20,
      paddingBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: Colors.border.light,
    },
    loginModalCloseButton: {
      alignSelf: 'flex-end',
      padding: 10,
    },
    loginModalTitle: {
      fontSize: 26,
      fontWeight: '700',
      color: Colors.text.dark,
      marginTop: 10,
      marginBottom: 8,
      textAlign: 'center',
    },
    loginModalSubtitle: {
      fontSize: 15,
      color: Colors.text.secondary,
      textAlign: 'center',
      lineHeight: 22,
    },
    loginModalContent: {
      flex: 1,
    },
    premiumHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 50,
      paddingBottom: 10,
    },
    premiumBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      shadowColor: Colors.accent.gold,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    premiumText: {
      color: theme.text.inverse,
      fontSize: 12,
      fontWeight: '800',
      marginLeft: 4,
    },
    headerLeftSection: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    swipeLimitBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.isDark ? 'rgba(242, 139, 130, 0.1)' : 'rgba(255, 107, 107, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.interactive.danger,
    },
    swipeLimitText: {
      color: theme.interactive.danger,
      fontSize: 12,
      fontWeight: '700',
      marginLeft: 4,
    },
    upgradePrompt: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 215, 0, 0.1)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: Colors.accent.gold,
    },
    upgradeText: {
      color: Colors.accent.gold,
      fontSize: 12,
      fontWeight: '600',
      marginLeft: 4,
    },
    locationBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 107, 107, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      marginRight: 8,
    },
    locationText: {
      color: Colors.accent.red,
      fontSize: 11,
      fontWeight: '600',
      marginLeft: 4,
    },
    headerRightSection: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    discoveryButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 6,
    },
    superLikeCounter: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(78, 205, 196, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    counterText: {
      color: Colors.accent.teal,
      fontSize: 12,
      fontWeight: '600',
      marginLeft: 4,
    },
    scrollContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 20,
      paddingBottom: 100,
      width: '100%',
      ...Platform.select({
        web: {
          paddingHorizontal: 0,
          marginHorizontal: 0,
        },
      }),
    },
    cardsContainer: {
      width: '100%',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: SCREEN_HEIGHT * 0.75,
      ...Platform.select({
        web: {
          maxWidth: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        },
      }),
    },
    cardsWrapper: {
      width: Platform.OS === 'web' ? '100%' : SCREEN_WIDTH,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: SCREEN_HEIGHT * 0.75,
      ...Platform.select({
        web: {
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        },
      }),
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 20,
      fontSize: 18,
      color: Colors.background.white,
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
      minHeight: 400,
    },
    emptyCard: {
      width: SCREEN_WIDTH - 40,
      borderRadius: 30,
      padding: 40,
      alignItems: 'center',
      shadowColor: Colors.text.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 15,
    },
    emptyTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: Colors.background.white,
      marginTop: 20,
      marginBottom: 15,
      textAlign: 'center',
    },
    emptyText: {
      fontSize: 16,
      color: Colors.text.white90,
      textAlign: 'center',
      lineHeight: 24,
      marginBottom: 20,
    },
    actionButton: {
      borderRadius: 25,
      overflow: 'hidden',
      marginTop: 10,
    },
    actionButtonGradient: {
      flexDirection: 'row',
      paddingVertical: 12,
      paddingHorizontal: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionButtonText: {
      color: Colors.primary,
      fontSize: 16,
      fontWeight: '700',
    },
    actionButtonsContainer: {
      position: 'absolute',
      bottom: 30,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
      gap: 15,
      ...Platform.select({
        web: {
          display: 'flex',
          width: '100%',
          marginLeft: 0,
          marginRight: 0,
        },
      }),
    },
    undoButton: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: Colors.background.white,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: Colors.text.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
      marginRight: 10,
    },
    dislikeButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      overflow: 'hidden',
      shadowColor: Colors.accent.red,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    superLikeButton: {
      width: 55,
      height: 55,
      borderRadius: 27.5,
      overflow: 'hidden',
      shadowColor: Colors.accent.teal,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    likeButton: {
      width: 70,
      height: 70,
      borderRadius: 35,
      overflow: 'hidden',
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    actionButtonCircle: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    disabledButton: {
      opacity: 0.6,
    },
    limitBadge: {
      position: 'absolute',
      top: -5,
      right: -5,
      backgroundColor: Colors.accent.red,
      borderRadius: 10,
      width: 20,
      height: 20,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: Colors.background.white,
    },
    aiQuickAccessContainer: {
      backgroundColor: Colors.background.white,
      borderBottomWidth: 1,
      borderBottomColor: Colors.background.light,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    aiHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    aiHeaderIcon: {
      marginRight: 8,
    },
    aiQuickAccessTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: Colors.text.dark,
    },
    aiButtonsGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    aiQuickButton: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderRadius: 10,
      backgroundColor: Colors.background.lightest,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: Colors.border.gray,
    },
    aiButtonLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: Colors.text.dark,
      marginTop: 6,
      textAlign: 'center',
    },
    skeletonCardSpacing: {
      marginBottom: 15,
    },
    gamificationSection: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: theme.background.card,
      borderBottomWidth: 1,
      borderBottomColor: theme.border.light,
    },
  });

export default getStyles;
