#!/bin/bash
# Script to add Firebase credentials to Render via their API
# Note: This requires Render API token - alternative is to add manually in dashboard

echo "Firebase credentials extracted from JSON file"
echo ""
echo "To add these to Render, you have two options:"
echo ""
echo "OPTION 1: Add via Render Dashboard (Recommended)"
echo "1. Go to: https://dashboard.render.com"
echo "2. Select: dating-app-backend service"
echo "3. Go to: Environment tab"
echo "4. Add these environment variables:"
echo ""
echo "   Key: FIREBASE_PROJECT_ID"
echo "   Value: my-project-de65d"
echo ""
echo "   Key: FIREBASE_CLIENT_EMAIL"
echo "   Value: firebase-adminsdk-fbsvc@my-project-de65d.iam.gserviceaccount.com"
echo ""
echo "   Key: FIREBASE_PRIVATE_KEY"
echo "   Value: [See FIREBASE_RENDER_VALUES.txt for the full private key]"
echo ""
echo "5. Click: Save Changes"
echo ""
echo "OPTION 2: Use Render CLI (if installed)"
echo "  render env:set FIREBASE_PROJECT_ID=my-project-de65d"
echo "  render env:set FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@my-project-de65d.iam.gserviceaccount.com"
echo "  render env:set FIREBASE_PRIVATE_KEY='[private key value]'"
echo ""
